on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu_latest
steps:
  - name: checkout source code
    uses: actions/checkout@v4
  - name: setup JDK-17
    uses: actions/setup-java@v4
    
  - name: print java and maven version
    run: |
      mvn -v
      java -version