name: Java CI with Maven, SonarQube, Docker, Trivy

on:
  push:
    branches:
      - master
      - project-01
    paths:
      - DevOps-30-Projects/**
  pull_request:
    branches:
      - master
    paths:
      - DevOps-30-Projects/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DevOps-30-Projects/DevOps-Project-01/Java-Login-App/

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and run tests with coverage
      run: mvn clean verify --batch-mode

    - name: Upload WAR artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: java-war
        path: DevOps-30-Projects/DevOps-Project-01/Java-Login-App/target/*.war

    - name: Run SonarQube scan
      if: success()
      env:
        SONAR_TOKEN: ${{ secrets.PS_SONAR_TOKEN }}
        PROJECT_KEY: ${{ secrets.PS_SONAR_PROJECT_KEY }}
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=$PROJECT_KEY \
        -Dsonar.organization=prathyakshps-sonar \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      
    - name: Install Trivy
      uses: aquasecurity/setup-trivy@v0.2.3
      with:
        version: v0.61.0
    
    - name: Scan Docker image with Trivy
      run: |
        docker build -t java-login-app:latest .
        trivy image --exit-code=0 --severity HIGH,CRITICAL java-login-app:latest
      working-directory: DevOps-30-Projects/DevOps-Project-01/Java-Login-App

    - name: login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: push docker image
      run: |
        docker tag java-login-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/java-login-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-login-app:latest


        
